// ⚙️ Auto-generated by tools/update_version.dart
// Do not edit manually.

const String appVersion = '1.1.0';
const String buildTime = '2026-02-04 20:00:00';

const String whatsNew = '''
📦 Version 1.1.0 Updates:
- 🛡️ Advanced RBAC: Implemented granular permission checks for all roles.
- 👑 Super User Role: Introduced restricted access for organization management to Super Users only.
- 📊 Management Reports: Added Day Summary and Sales Manager tracking to Dashboard.
- 🔒 Secure Infrastructure: Enhanced RLS policies and database security.
- 📦 Stock Transfers: Initial support for inter-store stock movement.
- 🧹 Quality: Resolved multiple Flutter analyze warnings and optimized routing.
''';
